services:
  my_budget_backend:
    container_name: my_budget_backend
    build: backend
    restart: always
    ports:
      - "8087:8087"
    depends_on:
      my_budget_db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://my_budget_db:5432/my_budget
      SPRING_DATASOURCE_USERNAME: evgeniabulis
      SPRING_DATASOURCE_PASSWORD: 04041995

  my_budget_db:
    container_name: my_budget_db
    image: postgres:13
    environment:
      POSTGRES_USER: evgeniabulis
      POSTGRES_PASSWORD: 04041995
      POSTGRES_DB: my_budget
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U evgeniabulis -d my_budget" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  my_budget_frontend:
    container_name: my_budget_frontend
    build:
      context: frontend
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:8087/my_budget}
        - VITE_WS_URL=${VITE_WS_URL:-ws://localhost:8087/my_budget/ws}
    depends_on:
      - my_budget_backend
    ports:
      - "3000:3000"

volumes:
  postgres-data: